### ISSUE TITLE
Keep the quick aliases for most common DateRegions (UTC, local, system)

### ISSUE THREAD

**Issue by TadeasKriz** [malcommac/SwiftDate#122]
The new `DateRegion` does not have the `UTCRegion` and `localRegion` methods for easy access to these regions. The proposed usage seems wordy `DateRegion(timeZoneRegion: TimeZoneNames.UTC)`. What was the motivation for removing the two functions?

**Comment by Hout** [comment]
The rationale is is that a date region should only be created once and to your liking. `localRegion` as you mention is de default mode if you leave the reference to a region out, so there should be minimal work on this.

`UTCRegion` is a region for UTC, UTC is used in airplanes and other global organisations which is rather specific. If you would need it to work with an absolute time, that is encapsulated in NSDate. You should have no need to refer to it as "UTC" and use something like "absoluteTime" instead. The latter describes the object much better.

What is the underlying issue here?

**Comment by TadeasKriz** [comment]
I have added UTCRegion function (I know it would be better for it to be a static constant property, but I already used it on some places when I was using SwiftDate 2.0) to do what I was doing before.

`NSDate().startOf(.Hour, inRegion: DateRegion.UTCRegion()) + 1.days + 1.hours`

I use the UTC, because I need to have some reference independent on user's local timezone. I think we can close this issue, I will just use the extension function. (I realized it after I opened the ticket yesterday)

**Comment by Hout** [comment]
Setting an absolute time  object like NSDate to the start of an hour implies the use of a time zone. Why would you use UTC for that? For Europe that would be ok, but India -for instance- has a time zone that is 30 minutes off the hour for UTC. 

Can you tell me more about your use case?

**Comment by Hout** [comment]
No reaction, closed
