### ISSUE TITLE
Prefered style: init vs func

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#126]
I wonder what a general best practice is when implementing conversion functionality.

Would we prefer:
- `A(b)`  - an initialiser of class A using object b as a parameter 
- `b.toA()` - a function of class B to produce a class A object

In case of SwiftDate, this would apply to e.g. `date.toString(format:)` where it could also be `String(fromDate:format:)`

**Comment by malcommac** [comment]
First one "exports", second "consumes"; I prefer the first one because it' "natural" to think "I've a date [object] and I want to transform it in a string" and not "I've a date and I want a string, so I need to start from a string (destination) and pass the object I want to transform (source)". Moreover, talking about the example you have said we should start from a String as class (static func) and not instance (instance method): another point to prefer the first solution IMHO.

**Comment by Hout** [comment]
In an event driven world this would be the way to go indeed. So pushing forward, we would have to make the following changes:

Initialiser | becomes function
-------------|-------------------------
DateRegion init(components:) | NSDateComponents func toDateRegion()  -> DateRegion
DateInRegion init(components:) | NSDateComponents func toDateInRegion() -> DateInRegion 
NSDate init(components:) | NSDateComponents func toDate() -> NSDate

We should also write this down in the design decisions. 

Do you agree?

**Comment by malcommac** [comment]
Yup

**Comment by Hout** [comment]
Made init(components) internal as they are still very beneficial internally.
68e121438f6934b1a15bf98410c2f85308cecea5

**Comment by Hout** [comment]
Realised in v3.0.0.
