### ISSUE TITLE
More Swifty way of dealing with time differences

### ISSUE THREAD

**Issue by Hout** [malcommac/SwiftDate#140]
Proposal:
```
let date1 = X
let date2 = Y

// Difference is a NSDateComponents object 
let difference = date1 - date2

// Get the difference in minutes, also an NSDateComponents object, but just the minute variable filled.
let differenceInMinutes = (date1 - date2).inUnits([.Minute]) 

// Consequently:
let differenceInHoursAndMinutes = (date1 - date2).inUnits([.Minute, .Hour])
let differenceInWeeks = (date1 - date2).inUnits([.WeekInYear])

// Now conversion to string comes a lot more natural:
let str = differenceInHoursAndMinutes.toString() // E.g. "1 hour and 3 minutes"
```

**Comment by malcommac** [comment]
As you said let `difference = date1 - date2` returns an `NSDateComponents` instance; so what's happens when you append `.inUnits([.Minute])`?
Should we get the resulting NSDate from  `date1 - date2`'s components and get only a subset of NSDateComponents value?

**Comment by Hout** [comment]
Not quite sure if I understand your question. I do not mean a subset but a different representation in the NSDateComponents object. Let me elaborate: 
```
let date1 = 18:50:00
let date2 = 19:51:03

let difference = date2 - date1 \\ = 1 hour, 1 minute, 3 seconds
let differenceInMinutes = difference.inUnits(.Minute) \\ = 61 minutes, seconds are ignored
let differenceInMinutesAndSeconds = difference.inUnits([.Minute, .Second]) \\ = 61 minutes, 3 seconds
```
Does this answer your question?

**Comment by malcommac** [comment]
Okay I got it right (but my solution does not work).
The problem is how to convert from a `NSDateComponents` to another (from a date components where all units are calculated to another where a different set of these should be calculated).
This because `date2 -  date1` results in a `NSDateComponents` instance and we have already lost references to both original dates... so how can we get another "style" of `NSDateComponents` with different units without a reference to the original dates?

**Comment by Hout** [comment]
You are correct! Working on this...

**Comment by Hout** [comment]
I implemented it with an NSDateInterval, ported to DateInRegion.
The NSDateFormatter produces nicely localised strings, but AAAAARGH its bugginess is much worse than you already stated :D
Check out feature/stringTests, file DateInIntervalInRegionStringTests.swift and look for “// Bug”.

I have come to a point where indeed I agree that we need to come with our own implementation.
Possibly port the TTT version. My idea is to somehow extract the formatting from NSLocale and not fill it ourselves.

Sometimes it requires hours and hours of work to come to insight, thanks for this ;-)

BUT!!! I think that first we need to create v3. We cannot continue with implementing good ideas and leave the library half broken at v2.
After that we can continue with the relativeString feature. Is that alright with you?

**Comment by malcommac** [comment]
As you said, I think we should move quickly to the next version in order to fix the broken parts of the current available version.
So IMHO we should fill the holes for:
- remaining tests for currently implemented methods (beside formatting is there anything else not covered? can you see this?)
- update documentation (I would to try to generate a jazzy apple style doc)

What do you think?

**Comment by Hout** [comment]
A few things are not covered, but the library does not need to be perfect. At least the basics are good now.
I will make a remark in the README that strings are still under construction.

The "release fast, fail fast" paradigm allows people to test code in ways that we cannot dream of, report the issue and allows us to fix and include it in the test code.

I will start the release check from the current develop branch.
While it is not merged into master, we can still alter things.

**Comment by malcommac** [comment]
[Implemented](http://malcommac.github.io/SwiftDate/extensions.html#timeinterval) since Swift 4.x.
