### ISSUE TITLE
ISO8601 Format issue

### ISSUE THREAD

**Issue by GUL-** [malcommac/SwiftDate#165]
I am experiencing issues when using SwiftDate built-in functions to serialize/deserialize dates from server in ISO8601 format.
example date from server:
`"2016-06-06T08:30:00+02:00"`

Changing date format from `"yyyy-MM-dd'T'HH:mm:ss:SSSS"` to `"yyyy-MM-dd'T'HH:mm:ssZZZZZ"`fixes the issue

**Comment by malcommac** [comment]
Regarding deserialization from string you should not have problems; for example
let d = "2016-06-06T08:30:00+02:00".toDate(DateFormat.ISO8601)
output NSDate is 
2016-06-06 06:30:00 +0000
which is correct.

About serialization this is a known issue; it should be fixed in develop branch (https://github.com/malcommac/SwiftDate/blob/develop/Sources/SwiftDate/NSDateFormatter%2BSwiftDate.swift#L78) and soon as we ready with relative date formatting it will be published.

**Comment by Hout** [comment]
Is this issue resolved now?

**Comment by malcommac** [comment]
Yes we can close it
