### ISSUE TITLE
Carthage fails

### ISSUE THREAD

**Issue by lololo** [malcommac/SwiftDate#219]
*** Fetching SwiftDate
*** Checking out SwiftDate at "3.0.9"
*** xcodebuild output can be found in /var/folders/8h/mdz9rybx5dv4jgg64fqz8k700000gp/T/carthage-xcodebuild.uuB0GU.log
*** Building scheme "SwiftDate-OSX" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-WatchOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-iOS" in SwiftDate.xcodeproj
*** Building scheme "SwiftDate-tvOS" in SwiftDate.xcodeproj
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Volumes/Transcend/Document/Malisa/Carthage/Checkouts/SwiftDate/XCode/SwiftDate.xcodeproj -scheme SwiftDate-tvOS -configuration Release -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by iandundas** [comment]
This is not related to SwiftDate, [please see this issue](https://github.com/Carthage/Carthage/issues/281) :)

**Comment by xandros6** [comment]
Hi, I have problem with Carthage too.
Simple `github "malcommac/SwiftDate"` on my Cartfile
carthage 0.17.2
xcode 7.3.1

When I run `carthage update --platform iOS --no-use-binaries`
The output is:

*** Skipped building SwiftDate due to the error:
Dependency "SwiftDate" has no shared framework schemes for any of the platforms: iOS

Other project in the same Cartfile works.
Thanks.

**Comment by malcommac** [comment]
Can you check with the new build?
