### ISSUE TITLE
Wrong display on actual device

### ISSUE THREAD

**Issue by kalwyn** [malcommac/SwiftDate#28]
On simulator, I am getting the proper display of about 1 day ago.

Upon moving to the device, I am getting the wrong display of about 9.223372e+18 wks ago.

**Comment by malcommac** [comment]
Hi,
Can you paste here your code? thanks

**Comment by kalwyn** [comment]
```` swift
var postedOn = post.createdAt!
post["timeAgo"] = postedOn.toRelativeString(fromDate: NSDate(), abbreviated: true, maxUnits: 1)
````

post.createdAt looks like this: 2015-08-07T16:39:44.703Z

**Comment by kalwyn** [comment]
Top right

![image](https://cloud.githubusercontent.com/assets/8174087/9312115/9fcf458c-44cf-11e5-925b-a160fbe18252.jpg)

**Comment by kalwyn** [comment]
Top right
![image](https://cloud.githubusercontent.com/assets/8174087/9312155/c2d5bb7e-44cf-11e5-9bc3-c130664c516d.jpg)

**Comment by malcommac** [comment]
Are you using SwiftDate from CocoaPods?

**Comment by kalwyn** [comment]
Yes.

**Comment by malcommac** [comment]
It should be an outdated version compared to the master one and this error should be a duplicate of this: https://github.com/malcommac/SwiftDate/issues/15.
However at this time I can't update cocoapods version with a new 1.0.11 build due to a GitHub's API error (I'll try to do it later today); however if you want to test, try to download the master release package and use it; everything should be ok.

**Comment by kalwyn** [comment]
Will do this later today when I'm off work. Thanks for the response.

**Comment by malcommac** [comment]
Just posted 1.0.11 to cocoapods

**Comment by kalwyn** [comment]
Works like a charm, thanks!

**Comment by malcommac** [comment]
Thanks for your report
