### ISSUE TITLE
Can not use SwiftDate in Xcode8+Swift2.3

### ISSUE THREAD

**Issue by tpian928** [malcommac/SwiftDate#282]
We use SwiftDate in Xcode8+Swift2.3 with pod

`pod 'SwiftDate', '~> 3.0.8'`

But there are a error 
**SwiftDate-Swift.h:256:1: Duplicate interface definition for class 'NSDateInterval'**

**Comment by mn288** [comment]
Delete that error, or rename that class to SDDateInterval

**Comment by malcommac** [comment]
Is possible to repost a cocoapod tagged release?

**Comment by mn288** [comment]
This is commented on the class when using Swift2.3.
This API is from Swift Foundation and it was a duplicate with a class with the SwiftDate Library

/// Alternative API from swift.org for avoiding AutoreleasingUnsafeMutablePointer usage in
/// NSCalendar and NSFormatter
/// - Experiment: This is a draft API currently under consideration for official import into
///   Foundation as a suitable alternative to the AutoreleasingUnsafeMutablePointer usage case of
///   returning a NSDate + NSTimeInterval or using a pair of dates representing a range
/// - Note: Since this API is under consideration it may be either removed or revised in the near
///   future
///

**Comment by malcommac** [comment]
try to use the branch instead of tagged version on cocoapods:

```
pod 'SwiftDate', git: 'https://github.com/malcommac/SwiftDate.git', branch: 'feature/swift_23'
```
