### ISSUE TITLE
timeIntervalSince1970 with Locale

### ISSUE THREAD

**Issue by adrimarti** [malcommac/SwiftDate#299]
I do not know how to get the `timeIntervalSince1970` with the default Locale of the device.

**Comment by malcommac** [comment]
I think I can't understand what you try to accomplish.
Want you get the `.timeIntervalSince1970` in device's locale? `.timeIntervalSince1970` is the absolute number of seconds since 1970 and the value is not related to a specific locale.
If you want to get the `.timeIntervalSince1970` from a `DateInRegion` object you can obtain it using `variabile.absoluteDate.timeIntervalSince1970`

**Comment by adrimarti** [comment]
I am using a third part library to represent my data on charts and I must provide the dates on the UNIXTimestamp format. 
Then, when I try to represent a date, it is shown as 2 hour before date because it is not taking the time with my current Locale.

**Comment by malcommac** [comment]
You can allocate a Date object without using DateInRegion via:
```swift
.init(timeIntervalSince1970: TimeInterval)
```swift
