### ISSUE TITLE
Default region is not set automatically to `Region.Local()`

### ISSUE THREAD

**Issue by balazsnemeth** [malcommac/SwiftDate#303]
The documentation of `public static func setDefaultRegion(_ region: Region?)` said "Default region is set automatically at runtime to `Region.Local()`"

*For me it remains the default GMT and it is not updated for local time automatically.* As a result when I try to use any Date adjustment, which I expected to results a local date for me, it resulted a date in GMT.

So I manually had to set the local region as default:

`Date.setDefaultRegion(Region.Local())`

Consider running the following example:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        print("11 AM: \(try? Date().atTime(hour: 11, minute: 0, second: 0))")
        print("tomorrow 9AM: \(Date().startOfDay + 1.days + 9.hours)")

        //Update the default region of the date to local instead of UTC
        Date.setDefaultRegion(Region.Local())

        print("11 AM: \(try? Date().atTime(hour: 11, minute: 0, second: 0))")
        print("tomorrow 9AM: \(Date().startOfDay + 1.days + 9.hours)")

        return true
}
```

for me (I'm in Budapest, CEST, UTC+02:00) the console log:
```
11 AM: Optional(2016-10-13 11:00:00 +0000)
tomorrow 9AM: 2016-10-14 09:00:00 +0000
11 AM: Optional(2016-10-13 09:00:00 +0000)
tomorrow 9AM: 2016-10-14 07:00:00 +0000
```

I think #279 also related this.

**Comment by balazsnemeth** [comment]
Any update on this?

**Comment by sigursalt** [comment]
Same here - just upgraded to 4.0 and my region default is GMT.  Had to manually set in AppDelegate for the time being.

**Comment by malcommac** [comment]
Fixed for 4.0.6 in feature/4.0.6 branch https://github.com/malcommac/SwiftDate/commit/e8c019a4d30797e5506a0d475922608d1768b33a

**Comment by afladmark** [comment]
However, in your documentation under [Default Region](http://malcommac.github.io/SwiftDate/main_concepts.html#default_region) you state: 

> As you may notice, when you work with plain Date object you are effectively working with a DateInRegion defined in a Date.defaultRegion; initially this a Region which has:
> 
> .timeZone set as GMT (Greenwich Mean Time)
> .locale set as the default device's locale
> .calendar set as the default device's calendar

So, as long as I've used this library (which admittedly is only since about 4.0.0), the default timezone behaviour has been GMT. In my case this "fix" represents a breaking change to my application... buried in a x.x.y pod update which thankfully I spotted.

I've always had to create DateInRegion objects to work with local times and I've used the default implementation for GMT on the basis of the above documentation. So now all my code is backwards!

I'm not actually debating whether you should make this change or which behaviour makes more sense -- that's entirely your call. I realise I can set the value back to GMT at app startup and that's what I'll do, but this change may have serious implications for some users as it would have for me. I simply don't believe the consequences or timing of this change was as well considered as it should have been, but please correct me if I've misunderstood something...

**Comment by andreyrd** [comment]
Prior to version 4.0.0, the default timezone behavior was local, not GMT.
