### ISSUE TITLE
 date.toString  format

### ISSUE THREAD

**Issue by idushes** [malcommac/SwiftDate#31]
From doc:
let string = date.toString(format: DateFormat.Custom("YYYY-MM-DD")) // something like "2015-01-01"

but if date 2015-02-01
let string = date.toString(format: DateFormat.Custom("YYYY-MM-DD")) // something like "2015-01-32"

**Comment by malcommac** [comment]
It's a mistake; day of the month format is "dd" not "DD". Just fixed it into the doc.
I've also added a summary sheet with all available formats strings into the README.md file.
(The following table is copied from this [original article](http://waracle.net/iphone-nsdateformatter-date-formatting-table/))

| Field    | Symbol | No   | Example                                                                                                                  | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|----------|--------|------|--------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| era      | G      | 1..3 | AD                                                                                                                       | Era Đ Replaced with the Era string for the current date. One to three letters for the abbreviated form, four letters for the long form, five for the narrow form.                                                                                                                                                                                                                                                                                                       |
|          |        | 4    | Anno Domini                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 5    | A                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| year     | y      | 1..n | 1996                                                                                                                     | Year. Normally the length specifies the padding, but for two letters it also specifies the maximum length. Example:                                                                                                                                                                                                                                                                                                                                                     |
|          | Y      | 1..n | 1997                                                                                                                     | Year (in ŇWeek of YearÓ based calendars). This year designation is used in ISO year-week calendar as defined by ISO 8601, but can be used in non-Gregorian based calendar systems where week date processing is desired. May not always be the same value as calendar year.                                                                                                                                                                                             |
|          | u      | 1..n | 4601                                                                                                                     | Extended year. This is a single number designating the year of this calendar system, encompassing all supra-year fields. For example, for the Julian calendar system, year numbers are positive, with an era of BCE or CE. An extended year value for the Julian calendar system assigns positive values to CE years and negative values to BCE years, with 1 BCE being year 0.                                                                                         |
| quarter  | Q      | 1..2 | 02                                                                                                                       | Quarter Đ Use one or two for the numerical quarter, three for the abbreviation, or four for the full name.                                                                                                                                                                                                                                                                                                                                                              |
|          |        | 3    | Q2                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 4    | 2nd quarter                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | q      | 1..2 | 02                                                                                                                       | Stand-Alone Quarter Đ Use one or two for the numerical quarter, three for the abbreviation, or four for the full name.                                                                                                                                                                                                                                                                                                                                                  |
|          |        | 3    | Q2                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 4    | 2nd quarter                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| month    | M      | 1..2 | 09                                                                                                                       | Month Đ Use one or two for the numerical month, three for the abbreviation, or four for the full name, or five for the narrow name.                                                                                                                                                                                                                                                                                                                                     |
|          |        | 3    | Sept                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 4    | September                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 5    | S                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | L      | 1..2 | 09                                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 3    | Sept                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 4    | September                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 5    | S                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | l      | 1    | *                                                                                                                        | Special symbol for Chinese leap month, used in combination with M. Only used with the Chinese calendar.                                                                                                                                                                                                                                                                                                                                                                 |
| week     | w      | 1..2 | 27                                                                                                                       | Week of Year.                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|          | W      | 1    | 3                                                                                                                        | Week of Month                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| day      | d      | 1..2 | 1                                                                                                                        | Date Đ Day of the month                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|          | D      | 1..3 | 345                                                                                                                      | Day of year                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|          | F      | 1    | 2                                                                                                                        | Day of Week in Month. The example is for the 2nd Wed in July                                                                                                                                                                                                                                                                                                                                                                                                            |
|          | g      | 1..n | 2451334                                                                                                                  | Modified Julian day. This is different from the conventional Julian day number in two regards. First, it demarcates days at local zone midnight, rather than noon GMT. Second, it is a local number; that is, it depends on the local time zone. It can be thought of as a single number that encompasses all the date-related fields.                                                                                                                                  |
| week day | E      | 1..3 | Tues                                                                                                                     | Day of week Đ Use one through three letters for the short day, or four for the full name, or five for the narrow name.                                                                                                                                                                                                                                                                                                                                                  |
|          |        | 4    | Tuesday                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 5    | T                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | e      | 1..2 | 2                                                                                                                        | Local day of week. Same as E except adds a numeric value that will depend on the local starting day of the week, using one or two letters. For this example, Monday is the first day of the week.                                                                                                                                                                                                                                                                       |
|          |        | 3    | Tues                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 4    | Tuesday                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 5    | T                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | c      | 1    | 2                                                                                                                        | Stand-Alone local day of week Đ Use one letter for the local numeric value (same as ÔeŐ), three for the short day, or four for the full name, or five for the narrow name.                                                                                                                                                                                                                                                                                              |
|          |        | 3    | Tues                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 4    | Tuesday                                                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          |        | 5    | T                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| period   | a      | 1    | AM                                                                                                                       | AM or PM                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| hour     | h      | 1..2 | 11                                                                                                                       | Hour [1-12]                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|          | H      | 1..2 | 13                                                                                                                       | Hour [0-23]                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|          | K      | 1..2 | 0                                                                                                                        | Hour [0-11]                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|          | k      | 1..2 | 24                                                                                                                       | Hour [1-24]                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|          | j      | 1..2 | n/a                                                                                                                      | This is a special-purpose symbol. It must not occur in pattern or skeleton data. Instead, it is reserved for use in APIs doing flexible date pattern generation. In such a context, it requests the preferred format (12 versus 24 hour) for the language in question, as determined by whether h, H, K, or k is used in the standard short time format for the locale, and should be replaced by h, H, K, or k before beginning a match against availableFormats data. |
| minute   | m      | 1..2 | 59                                                                                                                       | Minute. Use one or two for zero padding                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| second   | s      | 1..2 | 12                                                                                                                       | Second. Use one or two for zero padding.                                                                                                                                                                                                                                                                                                                                                                                                                                |
|          | S      | 1..n | 3456                                                                                                                     | Fractional Second Đ truncates (like other time fields) to the count of letters. (example shows display using pattern SSSS for seconds value 12.34567)                                                                                                                                                                                                                                                                                                                   |
|          | A      | 1..n | 69540000                                                                                                                 | Milliseconds in day. This field behaves exactly like a composite of all time-related fields, not including the zone fields. As such, it also reflects discontinuities of those fields on DST transition days. On a day of DST onset, it will jump forward. On a day of DST cessation, it will jump backward. This reflects the fact that is must be combined with the offset field to obtain a unique local time value.                                                 |
| zone     | z      | 1..3 | PDTfallbacks:HPG-8:00GMT-08:00                                                                                           | Time Zone Đ with the specific non-location format. Where that is unavailable, falls back to localized GMT format. Use one to three letters for the short format or four for the full format. In the short format, metazone names are not used unless the commonlyUsed flag is on in the locale.For more information about timezone formats, see Appendix J: Time Zone Display Names.                                                                                    |
|          |        | 4    | Pacific Daylight Timefallbacks:HPG-8:00GMT-08:00                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | Z      | 1..3 | -0800                                                                                                                    | Time Zone Đ Use one to three letters for RFC 822 format, four letters for the localized GMT format.For more information about timezone formats, see Appendix J: Time Zone Display Names.                                                                                                                                                                                                                                                                                |
|          |        | 4    | HPG+8:00fallbacks:GMT-08:00                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | v      | 1    | PT                                                                                                                       | Time Zone Đ with the generic non-location format. Where that is unavailable, uses special fallback rules given in Appendix J. Use one letter for short format, four for long format.For more information about timezone formats, see Appendix J: Time Zone Display Names.                                                                                                                                                                                               |
|          |        | 4    | Pacific Timefallbacks:Pacific Time (Canada)Pacific Time (Whitehorse)United States (Los Angeles) TimeHPG-8:35 - GMT-08:35 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|          | V      | 1    | PSTfallbacks:HPG-8:00GMT-08:00                                                                                           | Time Zone Đ with the same format as z, except that metazone timezone abbreviations are to be displayed if available, regardless of the value of commonlyUsed.For more information about timezone formats, see Appendix J: Time Zone Display Names.                                                                                                                                                                                                                      |
|          |        | 4    | United States (Los Angeles) Timefallbacks:HPG-8:35GMT-08:35                                                              | Time Zone Đ with the generic location format. Where that is unavailable, falls back to the localized GMT format. (Fallback is only necessary with a GMT-style Time Zone ID, like Etc/GMT-830.)This is especially useful when presenting possible timezone choices for user selection, since the naming is more uniform than the v format.For more information about timezone formats, see Appendix J: Time Zone Display Names.                                          |
