### ISSUE TITLE
How to get startOfDay in local time and convert to NSDate?

### ISSUE THREAD

**Issue by achirkof** [malcommac/SwiftDate#327]
Hi!
Could you explain how I can get startOfDay for local time and NSDate type?
My local time = GMT+3.
`Date().inLocalRegion().startOfDay` returns correct datetime but `DateInRegion` type.
`Date().inLocalRegion().startOfDay.absoluteDate` returns `Date` type but incorrect datetime(without timezone).

I need `Date` type because I have core data entity with property of type `Date` and I want to use NSPredicate to filter data. 
Thats why I have to create "today" date to put it in predicate:
```swift
let predicate = NSPredicate(format: "date == %@", today)
``` 
```
(lldb) po Date()
▿ 2016-11-04 23:22:55 +0000
  - timeIntervalSinceReferenceDate : 499994575.52093703


(lldb) po Date().inLocalRegion()
Nov 5, 2016, 2:23:00 AM GMT+3


(lldb) po Date().inLocalRegion().startOfDay
Nov 5, 2016, 12:00:00 AM GMT+3


(lldb) po Date().inLocalRegion().startOfDay.absoluteDate
▿ 2016-11-04 21:00:00 +0000
  - timeIntervalSinceReferenceDate : 499986000.0
```
Finally I have to add 3 hours(for my local timezone) to get correct start of a day
```
(lldb) po Date().startOfDay
▿ 2016-11-04 21:00:00 +0000
  - timeIntervalSinceReferenceDate : 499986000.0

(lldb) po Date().startOfDay.atTime(hour: 3, minute: 0, second: 0)
▿ 2016-11-05 00:00:00 +0000
  - timeIntervalSinceReferenceDate : 499996800.0
```

**Comment by malcommac** [comment]
Date objects does not belong any specific timezone.
It simply represent the absolute amount of time elapsed since an interval (even if it's not correct you can image it at the UTC timezone).
When you get the .absoluteDate from a DateInRegion object you are asking for the absolute representation of the time.
You should always store the timezone-indepentent value (plain Date/TimeInterval) and never the timezone related date.
