### ISSUE TITLE
DateInRegionFormatter crashes with any non-default allowed components

### ISSUE THREAD

**Issue by deville** [malcommac/SwiftDate#371]
The following code crashes with 4.0.10:

```swift
let from = DateInRegion() + 2.days
let to = DateInRegion()

let fmt = DateInRegionFormatter()
fmt.allowedComponents = [.day]

try fmt.colloquial(from: from, to: to).colloquial // crash here
```

The problem seems to be here:

```swift
public class DateInRegionFormatter {
    // ...
    public func colloquial(from fDate: DateInRegion, to tDate: DateInRegion) throws -> (colloquial: String, time: String?) {
	guard fDate.region.calendar == tDate.region.calendar else {
		throw DateError.DifferentCalendar
	}
	let cal = fDate.region.calendar
	let cmp = cal.dateComponents(self.allowedComponents, from: fDate.absoluteDate, to: tDate.absoluteDate)
	let isFuture = (fDate > tDate)
	
	if cmp.year != 0 { // this condition is true when cmp.year is nil
		// force unwrapping cmp.year results in crash 
		let colloquial_time = try self.colloquial_time(forUnit: .year, withValue: cmp.year!, date: fDate)
		// ...
	}
	// ...
```

**Comment by malcommac** [comment]
Thank you for your report; it's a bug because it try to unwrap and verify a component that is not part of the allowedComponents property.
I've just fixed it in this commit https://github.com/malcommac/SwiftDate/commit/94682dbc73f453d20d502f8ecf3e9d549ae73400.
It will be part of the 4.0.11 release.

Just a note:
When you do ```let from = DateInRegion() + 2.days``` you are adding 2 days to the current date+time, so unless the current datetime is midnight resulting colloquial string is like "tomorrow" (or yesterday, the difference is less than 1 day).
