### ISSUE TITLE
ISO8601 Parsing

### ISSUE THREAD

**Issue by lowki93** [malcommac/SwiftDate#395]
I would like like to create a region but it's failed : 

```swift
	let timeZone = TimeZone.current
        let calendar = Calendar.current
        let locale = Locale.current
        let region = Region(tz: timeZone, cal: calendar, loc: locale)
        do {
            return try DateInRegion(string: dateString,
                                    format: .iso8601(options: .withInternetDateTimeExtended),
                                    fromRegion: region).absoluteDate
        } catch let error {
            LogManager
                .sharedInstance
                .error("Failed formated string to date : '\(error)' -> '\(timeZone)' -> '\(calendar)' -> '\(locale)'")
        }
```

`timeZone`: Europe/Paris
`calendar`: gregorian
`locale`: fr_FR

My iPhone display hours in 12h not in 24h.
If I change it in 24h, it's work perfectly.

Why ??

**Comment by malcommac** [comment]
Hi, can you paste here `dateString`'s value?

**Comment by lowki93** [comment]
dateString : "2017-03-13T14:00:17.000Z"

**Comment by lowki93** [comment]
do you have an idea @malcommac  ?

**Comment by malcommac** [comment]
I've fixed the bug associated with your issue request: since 4.1.0 SwiftDate evaluates automatically the format used to parse ISO8601 date and generate a `Date` or `DateInRegion by reading the timezone into the string.
Moreover date parsing does not throws anymore, it just return `nil` if parse fails.
I'll release it later tomorrow.
Your parse is then much simpler, that's the code you will can use:

```swift
let date = DateInRegion(string: "2017-03-13T14:00:17.000Z", format: .iso8601Auto)
```

which returns:
```
Mar 13, 2017, 2:00:17 PM GMT
```

**Comment by lowki93** [comment]
Thanks, he works perfectly 👍

**Comment by lowki93** [comment]
I saw many log : Region is read from the string when ISO8601 parser is used
Can you remove it ;)
