### ISSUE TITLE
Using `colloquialSinceNow` with `DateComponentsFormatter.UnitsStyle.abbreviated`

### ISSUE THREAD

**Issue by tadija** [malcommac/SwiftDate#399]
Hi, thanks for this library!

I wanted to use colloquial feature of it, but with custom UnitsStyle (abbreviated), so I could get results like "1h", or "2m" and similar.

By short look at this method:
```swift
public func colloquialSinceNow(in region: Region? = nil, unitStyle: DateComponentsFormatter.UnitsStyle = .short, max: Int? = nil, zero: DateZeroBehaviour? = nil, separator: String? = nil) throws -> (colloquial: String, time: String?)
```
it seems to me that those input parameters are not forwarded or used later.

Is there something I'm missing here?

**Comment by malcommac** [comment]
Hi, you are right; since 4.1.0 both `colloquial` funcs for `Date` and `DateInRegion` accepts `style` property (`DateComponentsFormatter.UnitsStyle`) to specify the unit style of the formatter,.
Thank you.

Reference commit:
https://github.com/malcommac/SwiftDate/commit/0c23cb8adba2a3c2ef3716b9df8e75533be365de
