### ISSUE TITLE
Add rounding function to adjust/get date to nearest specified interval

### ISSUE THREAD

**Issue by ankraft** [malcommac/SwiftDate#408]
Would it be possible to add a rounding up/down method, for example to round to the next or previous quarter? This solution: http://stackoverflow.com/a/37261029/4799 on Stackover Overflow is a good example for this.

**Comment by malcommac** [comment]
Nice addition, added in https://github.com/malcommac/SwiftDate/commit/4bcd67ad4d3e0229ac717e1dddd2b5eae6ad3067. It will be available since 4.1.1.

`Date` and `DateInRegion` has now two functions to round a date to certain interval (expressed in `seconds` or `minutes`). `DateInRegion` exposes `roundAt()` which directly modify the date itself; `Date`, as immutable object, exposes the same feature in `roundedAt()` function (which return a new `Date` instances).

**Comment by ankraft** [comment]
Great, thanks a lot!
