### ISSUE TITLE
Colloquial result

### ISSUE THREAD

**Issue by alexsanderkhitev** [malcommac/SwiftDate#431]
Hello everyone! I updated SwiftDate to 4.1.2 version. I'm trying to get data, for example, after 3 hours and 15 minutes, but I can not achieve this accuracy, because minutes are not displayed, and if the value is less than an hour, I get the "now" result, how can I fix it? Thanks!

```
let formatter = DateInRegionFormatter()
                formatter.unitStyle = .full
                formatter.allowedComponents = [.year, .month, .day, .hour, .minute, .second]
                let nowDate = Date()
                do {
                    let result = try formatter.colloquial(from: cardDate.inRegion(), to: nowDate.inRegion())
                    debugPrint("result.colloquial is", result.colloquial, cardDate, "now date", Date())
                    return result.colloquial
                } catch {
                    debugPrint(error.localizedDescription, error)
                }
```

Console logs

`"result.colloquial is" "in 3 hours" 2017-05-09 08:00:00 +0000 "now date" 2017-05-09 04:51:11 +0000
`
`"result.colloquial is" "now" 2017-05-09 05:30:00 +0000 "now date" 2017-05-09 04:51:11 +0000
`

**Comment by etoledom** [comment]
I have the same issue where displaying colloquial time less than one hour old says always 'now', instead of i.e.: '45 minutes ago'.
 I saw the code on _**DateRegionFormatter.swift:185, func coloquial(from...**_
It seems like the line:
`if diff_in_hours < 24 && diff_days == 0 { ... }`

is always handling the colloquial formatting for any time less than one day old, so the string will be like 'now' -> 'one hour ago' -> '2 hours ago' ... etc.

The code that handles seconds and minutes differences seems to never be reached.

---
I had similar problem trying to display the string 'yesterday' instead of '35 hours ago' for time between 48 and 24 hours old

**Comment by dbaule** [comment]
Can confirm this issue.

**Comment by jeffersonsetiawan** [comment]
I think it because of [https://github.com/malcommac/SwiftDate/blob/master/Sources/SwiftDate/DateInRegionFormatter.swift#L210](url) part not checking lower than an hour.

**Comment by jeffersonsetiawan** [comment]
@malcommac can it merged to fix the issue?

**Comment by malcommac** [comment]
You will find it in 4.1.6.
Thank you
