### ISSUE TITLE
Patch to correct bad timezone with .net is not working

### ISSUE THREAD

**Issue by jojo91** [malcommac/SwiftDate#444]
Hi, I've tried your fix on the #427 issue and it seems that the issue is still here.
My test :

```swift
let myDotNetDate = "/Date(-2208992400000+0100)/"
if let date = myDotNetDate.date(format: .dotNET) {
    let newDate = date.absoluteDate
    print(myDotNetDate)
    print(newDate.string(format: .dotNET))
}
```
The result : 
```
/Date(-2208992400000+0100)/
/Date(-2208992400000+0000)/
```

**Comment by malcommac** [comment]
Hi, You are attempting to print a `Date` object using .NET formatter.
Using plain `Date` instances you are referring to an absolute time interval which does not contains informations about the timezone.
`Date/NSDate` represent absolute time intervals.
In order to correctly print your date as string you may want to print the `DateInRegion` instance you have created using `.date(format: .dotNET` function (`DateInRegion` instances include the `Region`, a struct with TimeZone, Locale and Calendar in which your date should be represented).
In fact printing your date from `date` var you will get the correct results:

```swift
let myDotNetDate = "/Date(-2208992400000+0100)/"
if let date = myDotNetDate.date(format: .dotNET) {
    print(date(format: .dotNET))
}
```

You will get

```
/Date(-2208992400000+0300)/
/Date(-2208992400000+0300)/
```
