### ISSUE TITLE
New ColloquialDateFormatter class (was colloquialSinceNow is incorrect)

### ISSUE THREAD

**Issue by alexanderkhitev** [malcommac/SwiftDate#492]
Hi! I use SwiftDate version 4.4.1. I use the `colloquialSinceNow` function for example the current time is 4:05, the event time was at 4:00, but this function returns "just now". How can I achieve the result in one minute without changing the framework? Thank you
`date.colloquialSinceNow(unitStyle: .full).colloquial`

**Comment by alexanderkhitev** [comment]
An example of an incorrect display. The time of the event is 1 hour 46 minutes and 16 seconds, and this function displays in an hour.
"colloquial" "in one hour" "nowDate" 2017-10-10 10:13:44 +0000 "eventDate" 2017-10-10 12:00:00 +0000

**Comment by wfilleman** [comment]
I'll add too, that the `max` param in `colloquialSinceNow` is ignored.

**Comment by jedmund** [comment]
I was using this library and ran into this, which forced me to switch away (especially since it never got fixed). Still haven't found a time ago/since now method I like so I might have to write something myself.

**Comment by malcommac** [comment]
Introduced a new `ColloquialDateFormatter` class in order to replace the old `DateInRegionFormatter` (now deprecated).
This class is specialized to format dates difference in colloquial format.

## DEPRECATED METHODS 
The following methods are now deprecated.

```swift
public func colloquialSinceNow(in region: Region? = nil, unitStyle: DateComponentsFormatter.UnitsStyle = .short, max: Int? = nil, zero: DateZeroBehaviour? = nil, separator: String? = nil) throws -> (colloquial: String, time: String?)
```

is replaced by:

```swift
public func colloquialSinceNow(in region: Region? = nil, options: ColloquialDateFormatter.Options? = nil) -> String?
```

---

```swift
public func colloquial(to: Date, in region: Region? = nil, max: Int? = nil, zero: DateZeroBehaviour? = nil, separator: String? = nil) throws -> (colloquial: String, time: String?)
```

is replaced by:

```swift
public func colloquial(to: Date, in region: Region? = nil, options: ColloquialDateFormatter.Options? = nil) -> String?
```

---

```swift
public func colloquialSinceNow(style: DateComponentsFormatter.UnitsStyle? = nil) throws -> (colloquial: String, time: String?)
```

is replaced by:

```swift
public func colloquialSinceNow(options: ColloquialDateFormatter.Options? = nil) -> String?
```

---

```swift
public func colloquial(toDate date: DateInRegion, style: DateComponentsFormatter.UnitsStyle? = nil) throws -> (colloquial: String, time: String?)
```

is replaced by:

```
public func colloquial(toDate date: DateInRegion, options: ColloquialDateFormatter.Options? = nil) -> String?
```

## HOW WORKS NEW CLASS

`ColloquialDateFormatter` is used automatically from the new functions above (or directly by calling its static functions:

```swift
public static func colloquial(from fDate: DateInRegion, to tDate: DateInRegion, options fOpt: ColloquialDateFormatter.Options? = nil) -> String?
```

It takes three arguments: dates to compare and a formatter options struct called `ColloquialDateFormatter.Options`.

`ColloquialDateFormatter.Options` define a set of parameters used to get the date using colloquial format:

* `allowedComponents`: Define the list of allowed components used to format a date diff. If you want exclude one or more time unit (ie. you are not interested in printing the weeks but you want to get only the days) you can set a different set of components (ie. [.day]). By default all components are allowed (`[.year, .month, .weekOfYear, .day, .hour, .minute, .second]`).
* `imminentRange`: Define the maximum amount of time used to fallback a dates difference to "just now" fallback. You need to express it in `DateComponents`, so if you want a "just now" result when difference is less than one hour and 5 minutes you need to set it to `1.hour + 5.minutes`. By default this value is set to `5.minutes`, so when difference is below five minutes the colloquial result return `just now` in set locale.
* `distantRange`: Define the minimum amount of time used to fallback a colloquial string to an absolute version of the data; for example if you set it to `2.months` when date diff is longer than 2 months you will get an absolute value (ie. `dd/MM` instead of `in 3 months`). By default this value is set to `nil` so fallback never occurs.
* `locale`: Define the locale used to produce colloquial string representation. If not set (`nil`) locale is taken from the `Region`'s `locale` of the first date but if you prefer you can force it to your own settings.

**Comment by malcommac** [comment]
Fixed issues:
* Fixed an issue where a difference between dates occurs crossing two days it was incorrectly reported (now it returns 'yesterday' or 'tomorrow' instead of the absolute number of hours'
* Fixed an issue with the imminent range which causes bad formatted strings with 'just now' when date diff is longer than interval set (old version was 5 minutes, now you can set it via `imminentRange`).
* Fixed an issue reporting the wrong weeks difference when dates diff is longer than 7 days.

**Comment by malcommac** [comment]
@alexanderkhitev 
To print by excluding the `just now` fallback you can now remove the `imminentRange`.
For example:

```swift
let d1 = DateInRegion()
let d2 = d1 + 5.minutes
var opts = ColloquialDateFormatter.Options()
opts.imminentRange = nil
let colloquial = d2.colloquial(toDate: d1, options: opts)
print(colloquial) // in 5 minutes (for en)
```

**Comment by malcommac** [comment]
Just released.
Tell me if it works fine for you so I'll add more unit tests.
Thanks.

**Comment by alexanderkhitev** [comment]
@malcommac I did not test a lot of these functions (now many other tasks), but those that tested worked well. Thank you so much!

**Comment by alexanderkhitev** [comment]
@malcommac I tried to use the colloquialSinceNow function and it does not work correctly. For example, the event after 2 hours 57 minutes and 30 seconds, and returns just now.

```
    private func colloquial(_ date: Date) -> String? {
        var opts = ColloquialDateFormatter.Options()
        opts.imminentRange = 1.minute
        let colloquial = date.inRegion().colloquialSinceNow(options: opts)
        debugPrint("now date", Date(), "date", date, "colloquial", colloquial ?? "")
        return colloquial
    }
```

Result 

`"now date" 2017-11-27 12:02:30 +0000 "date" 2017-11-27 15:00:00 +0000 "colloquial" "just now"
`

**Comment by alexanderkhitev** [comment]
@malcommac any news?

**Comment by malcommac** [comment]
@alexanderkhitev fixed and added your case to our unit tests. Please refer to #512 . Thank you
