### ISSUE TITLE
TimeInterval's in() function now alert when extracting calendar specific components without setting a reference date

### ISSUE THREAD

**Issue by loryhuz** [malcommac/SwiftDate#511]
Hi, time interval between two dates doesn't work in my app since my latest pod update.

```swift     
let currentDate = Date()
let test = currentDate + 3.month
print((test - currentDate).in(.month))
print((currentDate - test).in(.month))
```

Both results returns nil

Seems to be related to: https://github.com/malcommac/SwiftDate/commit/97a36756b7c7f66de56cef2e0ba6376e1cfcb13c

Can we consider it's wanted to work only with DateInRegion ?

EDIT:

Doesn't seems to work with DateInRegion either:

```
30 nov. 2017 à 15:45:31 UTC+1
28 févr. 2018 à 15:45:31 UTC+1
nil
nil

**Comment by malcommac** [comment]
The problem here is you can't evaluate calendar specific components (like months) without using a reference date where start the interval. This because months does not always contains the same number of days.
Old version uses current date plus the interval as reference settings.
I've restored the old behaviour but I've added an alert in debug using `debugPrint()`.

**Comment by loryhuz** [comment]
After some research I saw it was working with other components like days, hours. Seems legit ! Well done, thanks.
