### ISSUE TITLE
Not able to get local date using toLocalTime()

### ISSUE THREAD

**Issue by pratik6554** [malcommac/SwiftDate#55]

**Comment by malcommac** [comment]
Can you provide an example with results?

**Comment by pratik6554** [comment]
print("todays date ==\(NSDate())")
        print("toLocalTime ==\(NSDate().toLocalTime())")

output : 
todays date ==2015-10-19 08:42:45 +0000
toLocalTime ==2015-10-19 03:12:45 +0000

local time is not correct as per my time zone.

Please check http://www.davidbreyer.com/programming/2014/06/10/getting-local-date-and-time-with-swift/

**Comment by Fjohn666** [comment]
Hello. When I'l looking the toLocalTime function I think there is a problem : 
```
    func toLocalTime() -> NSDate {
        let tz : NSTimeZone = NSTimeZone.localTimeZone()
        let secs : Int = -tz.secondsFromGMTForDate(self)
        return NSDate(timeInterval: NSTimeInterval(secs), sinceDate: self)
    }
```
I think the seconds from GMT don't have to be always negative. For example I'm in France and GMT +2 time zone. The ToLocalTime is wrong for me here because it subtract 2hours of UTC and I need to add 2 hours ...

I'm wrong ?

**Comment by malcommac** [comment]
It should be fixed in https://github.com/malcommac/SwiftDate/pull/66
